name: switchScript_Tesla

on:
  workflow_dispatch:
  
  push:
    branches:
      - main
    paths:
      - '#README.md'
      - '#switchScript.sh'
      
  schedule:
    - cron: 0 4 * * *

env:
  SCRIPT_SH: ./.github/workflows/switchScript_Tesla.sh
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt install -y jq

    - name: "Build & Release"
      run: |
        echo "DATE=$(date "+%Y%m%d %H:%M:%S")" >> $GITHUB_ENV
        echo "tag_name=$(date +%Y%m%d)" >> $GITHUB_ENV
        chmod +x $SCRIPT_SH
        ./$SCRIPT_SH
        zip -rq SwitchSD-Tesla.zip SwitchSD-Tesla

    - name: Read description.txt
      id: description
      uses: juliangruber/read-file-action@v1
      with:
        path: ./description.txt

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        name: 心悦大气层中文整合包 v${{ env.DATE }} 
        allowUpdates: true
        tag: ${{ env.tag_name }}
        commit: main
        token: ${{ secrets.GITHUB_TOKEN }}
        body: "${{ steps.description.outputs.content }}"
        artifacts: "SwitchSD-Tesla.zip"

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.3.2
      with:
        keep_latest: 7
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
